vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_y3ig8v9l95q0:
                        id: node.app
                        hostname: node.app
                        network:
                            private_network: 192.168.56.90
                            forwarded_port:
                                vflmnfp_ju8hh4hqvkq1:
                                    host: '6340'
                                    guest: '22'
                                vflmnfp_942knf8rrg42:
                                    host: '55672'
                                    guest: '55672'
                                vflmnfp_vm2ijyonp7wm:
                                    host: '5672'
                                    guest: '5672'
                                vflmnfp_2kmmbpy5og4w:
                                    host: '1337'
                                    guest: '1337'
                        memory: '4096'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_lw4t91sda1:
                source: ./
                target: /var/www/node.app
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - curl
        - ssl-cert
        - mc
        - htop
users_groups:
    install: '1'
    groups: {  }
    users:
        - 'composer:www-data'
locale:
    install: '1'
    settings:
        default_locale: de_DE.UTF-8
        locales:
            - de_DE.UTF-8
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: Europe/Berlin
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_13ed9z0asdiu:
            server_name: node.app
            server_aliases:
                - node.app
            www_root: /var/www/node.app/public/
            listen_port: '80'
            index_files:
                - server.js
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '0'
            spdy: '1'
            locations:
                nxvl_fuguvc2ex74w:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                    location_cfg_append:
                      add_header:
                        'Service-Worker-Allowed': '/'
                nxvl_15pirq1u3iou:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                        - 'APP masterdata'
                    set:
                        - '$path_info $fastcgi_path_info;'
                        - 'gzip on;'
                        - 'gzip_proxied expired no-cache no-store private auth;'
                        - 'gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript application/font-woff'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
letsencrypt:
    install: '0'
    settings:
        email: ''
    domains: {  }
php:
    install: '0'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - curl
            - mcrypt
            - gd
            - imagick
            - mysqli
            - zip
            - bcmath
            - mbstring
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '6135'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        default_socket_timeout: '600'
        max_execution_time: '600'
        max_input_time: '600'
        post_max_size: 128M
        memory_limit: 2048M
        upload_max_filesize: 128M
        date.timezone=Europe/Berlin: '0'
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.idekey: PHPSTORM
        xdebug.remote_port: '9009'
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_log: /tmp/xdebug.log
        xdebug.profiler_enable: '0'
        xdebug.profiler_enable_trigger: '1'
        xdebug.profiler_output_dir: /tmp/
        xdebug.overload_var_dump: '0'
        xdebug.var_display_max_depth: '10'
        xdebug.remote_connect_back: '0'
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_wd74yosgxxkg:
            name: root
            password: 'root'
        mysqlnu_wd74yosgxxsf:
            name: 'nodeApp'
            password: '123'
    databases:
        mysqlnd_u31gygnnasrv:
            name: 'nodeApp'
            sql: ''
    grants:
        mysqlng_z25qv9add9g:
            user: root
            table: '*.*'
            privileges:
                - ALL
        mysqlng_z25qv9fredzh:
            user: nodeApp
            table: '*.*'
            privileges:
                - ALL
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
nodejs:
    install: '1'
    settings:
        version: '7'
    npm_packages:
      - gulp-cli
      - gulp